### ISSUE TITLE
Exercise Q2.b - difference of 3 tokens

### ISSUE THREAD

**Issue by meddulla** [LDSSA/batch2-BLU07#10]
I'm getting 1116 tokens in filtered text and the same difference of 3 in the unique tokens. It seems simple enough so I'm probably missing something obvious. 

My guess is that it's probably something to do with the punctuation removal - tried both using regex and string.punctuation, same result. 

If it helps, after stop words removal I have 1486 tokens.

Any ideas?

**Comment by meddulla** [comment]
Update: This is less urgent now since I had a passing grade but still curious about what I did wrong.

**Comment by CatarinaSilva** [comment]
Hello @meddulla I'm trying to understand how could that have happened, but could you maybe paste your solution here so I check the code?

**Comment by meddulla** [comment]
@CatarinaSilva I can paste it here but thought that went against the rules. Since it's submitted it should be in the platform. But I'll pm you.

**Comment by meddulla** [comment]
@CatarinaSilva Hmm, I ended pm'ing the wrong Catarina. What's your slack handle?

**Comment by CatarinaSilva** [comment]
@meddulla sorry, forgot about that, PM me then

**Comment by CatarinaSilva** [comment]
@meddulla  sorry, my slack handle is @Catarina but you need to select the one without picture

**Comment by CatarinaSilva** [comment]
To solve this, take in to account:

- The suggested tokeniser might be flawed and not be able to split some sets of punctuation, leaving some tokens as a mix of different punctuation symbols. `Eg: "(` . In this case, the token should not be removed since it does not appear in `string.punctuation`  

It is important for the solutions to match to handle the problem in a token-based manner and not character-based manner, this is, the string ` "(` should not be removed for this particular problem (in a world application this might be different)
