### ISSUE TITLE
Exercises: Q3 - Wrong order on list

### ISSUE THREAD

**Issue by manuelfcreis** [LDSSA/batch2-BLU07#5]
On the `answer` list from Q3 the final order is given by the count, however there are some items that have the same count.

I'm getting a different order from the one on the assert and failing because of this. What can I do?

**Comment by orlandocosta76** [comment]
I had the same problem, I copy-pasted the  result in the proper order.
I think there is a comment there implying it (though the assert has the answer):
_"# answer = ... (copy the output of the previous cell. It should be a list with 6 tuples)"_

**Comment by manuelfcreis** [comment]
@orlandocosta76 

Yeah I did the same, still feels a bit hackish 😅

**Comment by PedroMLF** [comment]
Yes, when I created the exercise I knew that would be an issue so I left the solution there on purpose. That way you can check you're getting the correct solution. Looking back, it could have be done differently in order to have a robust assert (making a set of that answer for instance) but back then I figured this approach would suffice.

**Comment by echo66** [comment]
@PedroMLF did you change the order **manually**? Or it your machine?

**Comment by PedroMLF** [comment]
The way it is in the notebook it's how it was ordered when I ran it.
